[versions]
agp = "8.5.2"
kotlin = "2.1.0"

androidx-paging = "3.3.6"
room = "2.6.1"
koinAndroid = "4.1.0-Beta5"
media3 = "1.5.1"
coil = "3.0.0-rc01"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.10.0" }

recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }

fragment = { module = "androidx.fragment:fragment-ktx", version = "1.8.6" }

splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
palette = { module = "androidx.palette:palette-ktx", version = "1.0.0" }

preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }


material = { group = "com.google.android.material", name = "material", version = "1.12.0" }


room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koinAndroid" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroid" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.14" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.1" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

[bundles]
androidx = [
    "androidx-core-ktx", "androidx-appcompat", "androidx-activity", "fragment",
    "recyclerview", "swiperefresh",
    "splashscreen", "palette",
    "preference"
]
paging = ["paging-common", "paging-runtime"]
room = ["room-runtime", "room-ktx"]
koin = ["koin-androidx-startup", "koin-android", "koin-androidx-workmanager"]
media3 = ["media3-exoplayer", "media3-session", "media3-ui", "media3-dash", "media3-hls"]
coil = ["coil", "coil-network-okhttp"]
kotlinx = ["kotlinx-serialization-json", "kotlinx-coroutines-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.0-1.0.29" }

